"""add votes table

Revision ID: 2fbcec3831dc
Revises: bad1e72e4613
Create Date: 2023-12-20 16:15:54.547375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fbcec3831dc'
down_revision: Union[str, None] = 'bad1e72e4613'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('basket_a')
    op.drop_table('basket_b')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('basket_b',
    sa.Column('b', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_b', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('b', name='basket_b_pkey')
    )
    op.create_table('basket_a',
    sa.Column('a', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fruit_a', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('a', name='basket_a_pkey')
    )
    # ### end Alembic commands ###
